version: '3'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "80:5000"
    environment:
      FLASK_SECRET_KEY: secret_key_2368
      DB_HOST: db
      DB_USER: postgres
      DB_DATABASE: warehouse
      DB_PASSWORD: password
  db:
    image: db
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse

